CREATE TABLE Usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    correo VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    telefono VARCHAR2(20),
    direccion VARCHAR2(255)
);
CREATE TABLE Categorias (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255),
    descripcion CLOB
);

CREATE TABLE Productos (
    id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion CLOB NOT NULL,
    precio NUMBER(10,2) NOT NULL,
    stock NUMBER NOT NULL,
    stock_inicial NUMBER,
    id_usuario NUMBER NOT NULL,
    id_categoria NUMBER NOT NULL,
    imagen_url VARCHAR2(255),

    CONSTRAINT fk_producto_usuario 
        FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario),

    CONSTRAINT fk_producto_categoria
        FOREIGN KEY (id_categoria) REFERENCES Categorias(id_categoria)
);

CREATE TABLE Carrito (
    id_carrito NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    id_usuario NUMBER,
    estado VARCHAR2(30) DEFAULT 'EN_PROCESO' NOT NULL,

    CONSTRAINT fk_carrito_usuario
        FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario)
);

CREATE TABLE Detalle_Carrito (
    id_detalle_carrito NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_carrito NUMBER NOT NULL,
    id_producto NUMBER NOT NULL,
    cantidad NUMBER NOT NULL,
    subtotal NUMBER(10,2) DEFAULT 0 NOT NULL,

    CONSTRAINT fk_detalle_carrito_carrito
        FOREIGN KEY (id_carrito) REFERENCES Carrito(id_carrito)
            ON DELETE CASCADE,

    CONSTRAINT fk_detalle_carrito_producto
        FOREIGN KEY (id_producto) REFERENCES Productos(id_producto)
);

CREATE TABLE HistorialVentas (
    id_venta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_carrito NUMBER NOT NULL,
    id_usuario NUMBER NOT NULL,
    fecha TIMESTAMP NOT NULL,
    total NUMBER(10,2) NOT NULL,

    CONSTRAINT fk_historial_carrito
        FOREIGN KEY (id_carrito) REFERENCES Carrito(id_carrito),

    CONSTRAINT fk_historial_usuario
        FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario)
);
